full_names = {
	"ari": "Arizona Diamondbacks",
	"atl": "Atlanta Braves",
	"bal": "Baltimore Orioles",
	"bos": "Boston Red Sox",
	"chi": "Chicago Cubs",
	"wsx": "Chicago White Sox",
	"cin": "Cincinnati Reds",
	"cle": "Cleveland Indians",
	"col": "Colorado Rockies",
	"det": "Detroit Tigers",
	"hou": "Houston Astros",
	"kc": "Kansas City Royals",
	"laa": "Los Angeles Angels",
	"la": "Los Angeles Dodgers",
	"mia": "Miami Marlins",
	"mil": "Milwaukee Brewers",
	"min": "Minnesota Twins",
	"nym": "New York Mets",
	"nyy": "New York Yankees",
	"oak": "Oakland Athletics",
	"phi": "Philadelphia Phillies",
	"pit": "Pittsburgh Pirates",
	"sd": "San Diego Padres",
	"sf": "San Francisco Giants",
	"sea": "Seattle Mariners",
	"stl": "St. Louis Cardinals",
	"tb": "Tampa Bay Rays",
	"tex": "Texas Rangers",
	"tor": "Toronto Blue Jays",
	"wsh": "Washington Nationals"
}