full_names = {
	"atl": "Atlanta Hawks",
	"bos": "Boston Celtics",
	"brk": "Brooklyn Nets",
	"cha": "Charlotte Hornets",
	"chi": "Chicago Bulls",
	"cle": "Cleveland Cavaliers",
	"dal": "Dallas Mavericks",
	"den": "Denver Nuggets",
	"det": "Detroit Pistons",
	"gs": "Golden State Warriors",
	"hou": "Houston Rockets",
	"ind": "Indiana Pacers",
	"lac": "Los Angeles Clippers",
	"lal": "Los Angeles Lakers",
	"mem": "Memphis Grizzlies",
	"mia": "Miami Heat",
	"mil": "Milwaukee Bucks",
	"min": "Minnesota Timberwolves",
	"no": "New Orleans Pelicans",
	"ny": "New York Knicks",
	"okc": "Oklahoma City Thunder",
	"orl": "Orlando Magic",
	"phi": "Philadelphia 76ers",
	"phx": "Phoenix Suns",
	"por": "Portland Trail Blazers",
	"sac": "Sacramento Kings",
	"sa": "San Antonio Spurs",
	"tor": "Toronto Raptors",
	"uth": "Utah Jazz",
	"wsh": "Washington Wizards"
}