full_names = {
	"ana": "Anaheim Ducks",
	"ari": "Arizona Coyotes",
	"bos": "Boston Bruins",
	"buf": "Buffalo Sabres",
	"cal": "Calgary Flames",
	"car": "Carolina Hurricanes",
	"chi": "Chicago Blackhawks",
	"col": "Colorado Avalanche",
	"clb": "Columbus Blue Jackets",
	"dal": "Dallas Stars",
	"det": "Detroit Red Wings",
	"edm": "Edmonton Oilers",
	"fla": "Florida Panthers",
	"la": "Los Angeles Kings",
	"min": "Minnesota Wild",
	"mon": "Montreal Canadiens",
	"nsh": "Nashville Predators",
	"nj": "New Jersey Devils",
	"nyi": "New York Islanders",
	"nyr": "New York Rangers",
	"otw": "Ottawa Senators",
	"phi": "Philadelphia Flyers",
	"pit": "Pittsburgh Penguins",
	"sj": "San Jose Sharks",
	"stl": "St. Louis Blues",
	"tb": "Tampa Bay Lightning",
	"tor": "Toronto Maple Leafs",
	"van": "Vancouver Canucks",
	"vgk": "Vegas Golden Knights",
	"wsh": "Washington Capitals",
	"win": "Winnipeg Jets"
}